# Generated by Django 5.2.1 on 2025-05-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_alter_usuario_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebooks',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smartphones',
            name='visivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
